
## Compute Pool
module "compute_default" {
  source                     = "git::https://github.com/gambol99/kube-tf-compute.git?ref=master"

  compute_asg_grace_period   = "${var.compute_asg_grace_period}"
  compute_asg_max            = "${var.compute_asg_max}"
  compute_asg_min            = "${var.compute_asg_min}"
  compute_docker_volume      = "${var.compute_docker_volume}"
  compute_docker_volume_type = "${var.compute_docker_volume_type}"
  compute_flavor             = "${var.compute_flavor}"
  compute_labels             = "${var.compute_labels}"
  compute_name               = "default"
  compute_root_volume        = "${var.compute_root_volume}"
  coreos_image               = "${var.coreos_image}"
  coreos_image               = "${var.coreos_image}"
  coreos_image_owner         = "${var.coreos_image_owner}"
  enable_calico              = "${var.enable_calico}"
  environment                = "${var.environment}"
  etcd_memberlist            = "${module.master.etcd_members_url}"
  flannel_memberlist         = "${module.master.flannel_members_url}"
  kms_master_id              = "${var.kms_master_id}"
  kubeapi_dns                = "${module.api.kubeapi_internal_dns}"
  kubernetes_image           = "${var.kubernetes_image}"
  private_zone_name          = "${var.private_zone_name}"
  public_zone_name           = "${var.public_zone_name}"
  secrets_bucket_name        = "${var.secrets_bucket_name}"

  aws_region                 = "${var.aws_region}"
  compute_sg                 = "${module.platform.compute_sg}"
  compute_subnets            = "${module.platform.compute_subnets}"
  elb_sg                     = "${module.platform.elb_sg}"
  elb_subnets                = "${module.platform.elb_subnets}"
  key_name                   = "${module.platform.key_name}"
  mgmt_sg                    = "${module.platform.mgmt_sg}"
  mgmt_subnets               = "${module.platform.mgmt_subnets}"
  nat_sg                     = "${module.platform.nat_sg}"
  nat_subnets                = "${module.platform.nat_subnets}"
  private_zone               = "${module.platform.private_zone}"
  public_zone                = "${module.platform.public_zone}"
  secure_sg                  = "${module.platform.secure_sg}"
  secure_subnets             = "${module.platform.secure_subnets}"
  vpc_id                     = "${module.platform.vpc_id}"
}
