
## Kuberneres Master
module "master" {
  source                   = "git::https://github.com/gambol99/kube-tf-master.git?ref=master"

  coreos_image             = "${var.coreos_image}"
  coreos_image_owner       = "${var.coreos_image_owner}"
  enable_calico            = "${var.enable_calico}"
  environment              = "${var.environment}"
  flannel_cidr             = "${var.flannel_cidr}"
  kms_master_id            = "${var.kms_master_id}"
  kubeapi_internal_dns     = "${var.kubeapi_internal_dns}"
  kubernetes_image         = "${var.kubernetes_image}"
  private_zone_name        = "${var.private_zone_name}"
  public_zone_name         = "${var.public_zone_name}"
  secrets_bucket_name      = "${var.secrets_bucket_name}"
  secure_asg_grace_period  = "${var.secure_asg_grace_period}"
  secure_data_encrypted    = "${var.secure_data_encrypted}"
  secure_data_volume       = "${var.secure_data_volume}"
  secure_data_volume_type  = "${var.secure_data_volume_type}"
  secure_docker_volume     = "${var.secure_docker_volume}"
  secure_flavor            = "${var.secure_flavor}"
  secure_nodes             = "${var.secure_nodes}"
  secure_nodes_asg         = "${var.secure_nodes_asg}"
  secure_nodes_zones       = "${var.secure_nodes_zones}"
  secure_root_volume       = "${var.secure_root_volume}"

  aws_region               = "${var.aws_region}"
  compute_sg               = "${module.platform.compute_sg}"
  compute_subnets          = "${module.platform.compute_subnets}"
  elb_sg                   = "${module.platform.elb_sg}"
  elb_subnets              = "${module.platform.elb_subnets}"
  key_name                 = "${module.platform.key_name}"
  mgmt_sg                  = "${module.platform.mgmt_sg}"
  mgmt_subnets             = "${module.platform.mgmt_subnets}"
  nat_sg                   = "${module.platform.nat_sg}"
  nat_subnets              = "${module.platform.nat_subnets}"
  private_zone             = "${module.platform.private_zone}"
  public_zone              = "${module.platform.public_zone}"
  secure_sg                = "${module.platform.secure_sg}"
  secure_subnets           = "${module.platform.secure_subnets}"
  vpc_id                   = "${module.platform.vpc_id}"
}

# Kuberneres API
module "api" {
  source                   = "git::https://github.com/gambol99/kube-tf-api.git?ref=master"

  environment              = "${var.environment}"
  kubeapi_access_list      = "${var.kubeapi_access_list}"
  kubeapi_dns              = "${var.kubeapi_dns}"
  kubeapi_external_elb     = "${var.kubeapi_external_elb}"
  kubeapi_internal_dns     = "${var.kubeapi_internal_dns}"
  private_zone_name        = "${var.private_zone_name}"
  public_zone_name         = "${var.public_zone_name}"
  secure_asg_size          = "${length(var.secure_nodes_asg)/2}"

  aws_region               = "${var.aws_region}"
  compute_sg               = "${module.platform.compute_sg}"
  compute_subnets          = "${module.platform.compute_subnets}"
  elb_sg                   = "${module.platform.elb_sg}"
  elb_subnets              = "${module.platform.elb_subnets}"
  mgmt_sg                  = "${module.platform.mgmt_sg}"
  mgmt_subnets             = "${module.platform.mgmt_subnets}"
  private_zone             = "${module.platform.private_zone}"
  public_zone              = "${module.platform.public_zone}"
  secure_sg                = "${module.platform.secure_sg}"
  secure_subnets           = "${module.platform.secure_subnets}"
  vpc_id                   = "${module.platform.vpc_id}"
}
